mysql:
    image: docker.io/centos/mysql-57-centos7
    restart: always
    volumes:
         - /docker-airflow_3.7/mariadb_data:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_USER=airflow
        - MYSQL_PASSWORD=airflow
        - MYSQL_DATABASE=airflow

rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
        - RABBITMQ_DEFAULT_USER=airflow
        - RABBITMQ_DEFAULT_PASS=airflow
        - RABBITMQ_DEFAULT_VHOST=airflow

webserver:
    image: tclezhil/airflow-python3.6
    restart: always
    volumes:
         - /data-ansible:/data-ansible
         - /docker-airflow_3.7/audit_app/audit_tool_server_data/airflow_dags:/opt/airflow/dags
         - /docker-airflow_3.7/logs:/opt/airflow/logs
         - /docker-airflow_3.7/audit_app:/audit_app
    environment:
        - AIRFLOW_HOME=/opt/airflow
    ports:
        - "8080:8080"
    links:
        - mysql:mysql
        - rabbitmq:rabbitmq
        - worker:worker
        - scheduler:scheduler
    command: webserver

flower:
    image: tclezhil/airflow-python3.6
    restart: always
    environment:
        - AIRFLOW_HOME=/opt/airflow
    ports:
        - "5555:5555"
    links:
        - mysql:mysql
        - rabbitmq:rabbitmq
    command: flower

scheduler:
    image: tclezhil/airflow-python3.6
    restart: always
    volumes:
        - /data-ansible:/data-ansible
        - /docker-airflow_3.7/audit_app/audit_tool_server_data/airflow_dags:/opt/airflow/dags
        - /docker-airflow_3.7/logs:/opt/airflow/logs
        - /docker-airflow_3.7/audit_app:/audit_app
    environment:
        - AIRFLOW_HOME=/opt/airflow
    links:
        - mysql:mysql
        - rabbitmq:rabbitmq
    command: scheduler

worker:
    image: tclezhil/airflow-python3.6
    restart: always
    volumes:
        - /data-ansible:/data-ansible
        - /docker-airflow_3.7/audit_app/audit_tool_server_data/airflow_dags:/opt/airflow/dags
        - /docker-airflow_3.7/logs:/opt/airflow/logs
        - /docker-airflow_3.7/audit_app:/audit_app
    environment:
        - AIRFLOW_HOME=/opt/airflow
    ports:
        - "8793:8793"
    links:
        - mysql:mysql
        - rabbitmq:rabbitmq
    command: worker
